queue_rules:
  - name: default
    queue_conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success~=^Test python
      - status-success~=^Build & publish package to pypi
      - status-success~=^Build docs on ubuntu-latest
      - status-success~=^Build docs on macos-latest
      - status-success~=docs/readthedocs.org
    merge_conditions:
      - check-success~=^Test python
      - check-success~=^Build & publish package to pypi
      - check-success~=^Build docs on ubuntu-latest
      - check-success~=^Build docs on macos-latest
      - check-success~=docs/readthedocs.org
    merge_method: rebase

pull_request_rules:
  - name: automatic merge
    conditions: []
    actions:
      queue:
