---
pull_request_rules:
  - actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success~=Test python
      - status-success~=Build & publish package to pypi
      - status-success~=Build docs on ubuntu-latest
      - status-success~=Build docs on macos-latest
      - status-success~=docs/readthedocs.org
    name: default
