---
jobs:
  - job: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        Python34:
          python.version: '3.4'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          python bootstrap.py
          bin/buildout install scripts crate test linter
        displayName: 'Install dependencies'

      - script: |
          bin/flake8
          JAVA_HOME=$JAVA_HOME_12_X64 bin/coverage run bin/test -vv1t test_cmd_line_sys_info
        displayName: 'test'
