---
name: release
on: release
jobs:
  pypi:
    name: Build & publish package to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build package
        run: |
          python -m pip install twine wheel
          python setup.py sdist bdist_wheel
          twine check dist/*.tar.gz

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

  bundle:
    name: Upload crash bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build bundle
        run: |
          python -m pip install shiv
          shiv -p /usr/bin/python3 -c crash -o ./crash crash==${{ github.ref }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: crash
          asset_name: crash
          asset_content_type: application/zip
